# Generated by Django 2.2 on 2020-07-04 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200704_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 12, 28, 45, 708881)),
        ),
    ]
